[project]
name = "Themerr-plex"
version = "0.0.0"
description = "Standalone theme song manager for Plex."
repository = "https://github.com/LizardByte/Themerr-plex"
author = "LizardByte"
logo = "web/images/icon-default.png"
favicon = "web/images/favicon.ico"

[build]
output = "_site"
work = ".dockle"
strict = true
clean = true

[[targets]]
name = "docs"
title = "Themerr-plex documentation"
framework = "sphinx"
source = "docs/source"
home = true

[targets.sphinx]
exclude_patterns = ["toc.rst"]
extra_config = "docs/dockle_sphinx.py"
source_edit_link = "https://github.com/LizardByte/Themerr-plex/blob/master/docs/source/{filename}"
