---
name: localize

env:
  PYTHON_VERSION: '3.14'

on:
  push:
    branches:
      - master
    paths:  # prevents workflow from running unless these files change
      - '.github/workflows/localize.yml'
      - 'locale/themerr-plex.po'
      - 'src/**.py'
      - 'web/templates/**'
  workflow_dispatch:

jobs:
  localize:
    name: Update Localization
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Install Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7  # v10.2.0

      - name: Setup Python Dependencies
        run: uv sync --locked --no-install-project --no-python-downloads --python ${{ env.PYTHON_VERSION }}

      - name: Update Strings
        run: uv run --locked --no-sync python ./scripts/_locale.py --extract

      - name: git diff
        run: |
          # disable the pager
          git config --global pager.diff false

          # print the git diff
          git diff locale/themerr-plex.po

          # set the variable with minimal output, replacing `\t` with ` `
          OUTPUT=$(git diff --numstat locale/themerr-plex.po | sed -e "s#\t# #g")
          echo "git_diff=${OUTPUT}" >> "$GITHUB_ENV"

      - name: git reset
        if: ${{ env.git_diff == '1 1 locale/themerr-plex.po' }}  # only run if more than 1 line changed
        run: git reset --hard

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Create/Update Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            locale/*.po
          token: ${{ secrets.GH_BOT_TOKEN }}  # must trigger PR tests
          commit-message: "chore(l10n): new babel updates"
          branch: localize/update
          delete-branch: true
          base: master
          title: "chore(l10n): new babel updates"
          body: |
            Update report
            - Updated ${{ steps.date.outputs.date }}
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            babel
            l10n
